Update pre-commit-hooks to check if tool exists first

diff --git a/tools/hooks/pre-commit-clang-format b/tools/hooks/pre-commit-clang-format
--- a/tools/hooks/pre-commit-clang-format
+++ b/tools/hooks/pre-commit-clang-format
@@ -1,6 +1,12 @@
 #!/bin/sh
 # Git pre-commit hook that runs a clang-format style check.
 
+if ! command -v clang-format > /dev/null; then
+	echo "Error: 'clang-format' executable not found."
+    echo "Please install clang-format, and try again."
+	exit 1
+fi
+
 # The application and options.
 application_name="clang-format"
 options="--Wno-error=unknown"
diff --git a/tools/hooks/pre-commit-documentation-checks b/tools/hooks/pre-commit-documentation-checks
--- a/tools/hooks/pre-commit-documentation-checks
+++ b/tools/hooks/pre-commit-documentation-checks
@@ -1,6 +1,12 @@
 #!/bin/sh
 # Git pre-commit hook that checks the API XML documentation spelling and syntax.
 
+if ! command -v codespell > /dev/null; then
+	echo "Error: 'codespell' executable not found."
+    echo "Please install codespell, and try again."
+	exit 1
+fi
+
 # Set exit on error.
 set -e
 
